name: "FlyCI Wingman"
description: "Automatically Fix Your Failing CI Builds"
inputs:
  wingman-url:
    description: "The URL to use for Wingman"
    required: false
  flyci-url:
    description: "The URL to use for Wingman"
    required: false
branding:
  icon: check-circle
  color: purple

runs:
  using: "node20"
  main: "dist/index.js"
